version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build_lint_test:
    machine:
      image: ubuntu-2204:2022.10.1
      resource_class: large
    steps:
      - checkout
      - run:
          name: Print Go environment
          command: "go env"
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v6-{{ checksum "go.sum" }}
      - run:
          name: Build
          command: make build
      - save_cache:
          key: go-mod-v6-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/.go_workspace/pkg/mod"
      - run:
          name: Lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.1
            ./bin/golangci-lint run
      - run:
          name: Run tests
          command: |
            make test

  build_docker:
    machine:
      image: ubuntu-2204:2022.10.1
      resource_class: large
    steps:
      - checkout
      - aws-ecr/build-image:
          push-image: false
          dockerfile: Dockerfile
          path: ./
          build-path: ./
          tag: "$CIRCLE_SHA1,$CIRCLE_TAG"
          repo: "$CIRCLE_PROJECT_REPONAME"
      - run:
          name: Save Docker image to export it to workspace
          command: |
            docker save $(docker image ls --format '{{.Repository}}:{{.Tag}}') > /tmp/babylon-relayer.tar
      - persist_to_workspace:
          root: /tmp
          paths:
            - babylon-relayer.tar

  push_docker:
    machine:
      image: ubuntu-2204:2022.10.1
      resource_class: large
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image from workspace
          command: |
            docker load -i /tmp/babylon-relayer.tar
      - aws-ecr/ecr-login:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: "$AWS_REGION"
      - aws-ecr/push-image:
          registry-id: AWS_ECR_REGISTRY_ID
          region: "$AWS_REGION"
          repo: "$CIRCLE_PROJECT_REPONAME"
          tag: "$CIRCLE_SHA1,$CIRCLE_TAG"

workflows:
  CI:
    jobs:
      - build_lint_test
      - build_docker:
          filters:
            tags:
              only: /.*/
      - push_docker:
          requires:
            - build_docker
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - main
                - dev
