global:
    api-listen-addr: :5183
    timeout: 20s
    memo: ""
    light-cache-size: 10
chains:
    babylon:
        type: cosmos
        value:
            key: babylon-key
            chain-id: bbn-demo1
            rpc-addr: http://rpc0.demo.babylonchain.io:26657
            account-prefix: bbn
            keyring-backend: test
            gas-adjustment: 1.5
            gas-prices: 0.002ubbn
            min-gas-amount: 1
            debug: true
            timeout: 10s
            output-format: json
            sign-mode: direct
            extra-codecs: []
    akash:
        type: cosmos
        value:
            chain-id: sandbox
            rpc-addr: http://rpc.sandbox.ny.aksh.pw:26657
            keyring-backend: test
            timeout: 10s
    injective:
        type: cosmos
        value:
            chain-id: injective-888
            rpc-addr: http://176.9.147.152:26657
            keyring-backend: test
            timeout: 10s
            extra-codecs:
                - injective
    juno:
        type: cosmos
        value:
            chain-id: uni-6
            rpc-addr: https://uni-rpc.reece.sh:443
            keyring-backend: test
            timeout: 10s
    osmosis:
        type: cosmos
        value:
            chain-id: osmo-test-4
            rpc-addr: https://osmosis-testnet-rpc.allthatnode.com:26657/
            keyring-backend: test
            timeout: 10s
    secret:
        type: cosmos
        value:
            chain-id: pulsar-2
            rpc-addr: https://rpc.pulsar.scrttestnet.com:443
            keyring-backend: test
            timeout: 10s
    sei:
        type: cosmos
        value:
            chain-id: atlantic-1
            rpc-addr: https://rpc-sei-ia.cosmosia.notional.ventures:443
            keyring-backend: test
            timeout: 10s
    stargaze:
        type: cosmos
        value:
            chain-id: elgafar-1
            rpc-addr: https://rpc.elgafar-1.stargaze-apis.com:443
            keyring-backend: test
            timeout: 10s
    desmos:
        type: cosmos
        value:
            chain-id: morpheus-apollo-3
            rpc-addr: https://rpc.morpheus.desmos.network:443
            keyring-backend: test
            timeout: 10s
paths:
    akash:
        src:
            chain-id: bbn-demo1
        dst:
            chain-id: sandbox
        src-channel-filter:
            rule: ""
            channel-list: []
    injective:
        src:
            chain-id: bbn-demo1
        dst:
            chain-id: injective-888
        src-channel-filter:
            rule: ""
            channel-list: []
    juno:
        src:
            chain-id: bbn-demo1
        dst:
            chain-id: uni-6
        src-channel-filter:
            rule: ""
            channel-list: []
    osmosis:
        src:
            chain-id: bbn-demo1
        dst:
            chain-id: osmo-test-4
        src-channel-filter:
            rule: ""
            channel-list: []
    secret:
        src:
            chain-id: bbn-demo1
        dst:
            chain-id: pulsar-2
        src-channel-filter:
            rule: ""
            channel-list: []
    sei:
        src:
            chain-id: bbn-demo1
        dst:
            chain-id: atlantic-1
        src-channel-filter:
            rule: ""
            channel-list: []
    stargaze:
        src:
            chain-id: bbn-demo1
        dst:
            chain-id: elgafar-1
        src-channel-filter:
            rule: ""
            channel-list: []
    desmos:
        src:
            chain-id: bbn-demo1
        dst:
            chain-id: morpheus-apollo-3
        src-channel-filter:
            rule: ""
            channel-list: []